// resources/js/Pages/Modals/PublishTranslations.tsx
import React, { useState } from "react";
import { message, Modal, Button, Alert, Spin } from "antd";
import { ArrowDownTrayIcon } from "@heroicons/react/24/outline";

interface PublishTranslationsProps {
    isOpen: boolean;
    onClose: () => void;
    canPublish: boolean;
    isProductionEnv: boolean;
}

const PublishTranslations: React.FC<PublishTranslationsProps> = ({
    isOpen,
    onClose,
    canPublish,
    isProductionEnv,
}) => {
    const [loading, setLoading] = useState(false);
    const [downloadLoading, setDownloadLoading] = useState(false);

    const handlePublish = async () => {
        try {
            setLoading(true);
            const response = await window.axios.post(route('ltu.translation.publish'));
            if (response.status === 200) {
                message.success('Translations published successfully');
                onClose();
            }
        } catch (error) {
            message.error('Failed to publish translations');
        } finally {
            setLoading(false);
        }
    };

    const handleDownload = async () => {
        try {
            setDownloadLoading(true);
            const response = await window.axios.get(route('ltu.translation.download'), {
                responseType: 'blob',
            });
            
            // Create a blob URL and trigger download
            const url = window.URL.createObjectURL(new Blob([response.data]));
            const link = document.createElement('a');
            link.href = url;
            link.setAttribute('download', 'lang.zip');
            document.body.appendChild(link);
            link.click();
            link.parentNode?.removeChild(link);
            window.URL.revokeObjectURL(url);
            
            onClose();
        } catch (error) {
            message.error('Something went wrong, please try again.');
        } finally {
            setDownloadLoading(false);
        }
    };

    const content = canPublish ? (
        <>
            <div className="mb-4">
                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                    Publish Translations
                </h3>
                <p className="text-gray-600">
                    Your translations are ready to be published. Click the button below to export
                    your translations and make them available in your application.
                </p>
            </div>

            {isProductionEnv && (
                <Alert
                    message="Production Environment"
                    description="You are in a production environment. Please download your translations first before publishing."
                    type="warning"
                    showIcon
                    className="mb-4"
                />
            )}
        </>
    ) : (
        <div className="flex flex-col items-center justify-center py-8">
            <div className="text-center">
                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                    No Languages to Publish
                </h3>
                <p className="text-gray-600">
                    You need to add at least one language before you can publish translations.
                </p>
            </div>
        </div>
    );

    return (
        <Modal
            title="Publish Translations"
            open={isOpen}
            onCancel={onClose}
            footer={[
                <Button key="close" onClick={onClose}>
                    Close
                </Button>,
                canPublish && (
                    <Button
                        key="download"
                        type="default"
                        icon={<ArrowDownTrayIcon className="size-5" />}
                        onClick={handleDownload}
                        loading={downloadLoading}
                        disabled={loading || downloadLoading}
                    >
                        Download
                    </Button>
                ),
                canPublish && !isProductionEnv && (
                    <Button
                        key="publish"
                        type="primary"
                        onClick={handlePublish}
                        loading={loading}
                        disabled={loading || downloadLoading}
                    >
                        Publish
                    </Button>
                ),
            ]}
        >
            <Spin spinning={loading || downloadLoading}>
                {content}
            </Spin>
        </Modal>
    );
};

export default PublishTranslations;

// resources/views/pages/translations/modals/publish-translations.vue
<script setup lang="ts">

import { ArrowDownTrayIcon } from "@heroicons/vue/16/solid";
import {POSITION, useToast} from "vue-toastification";

defineProps<{
    canPublish: boolean
    isProductionEnv: boolean
}>()

const toast = useToast()

const { close } = useModal()

const loading = ref(false)
const downloadLoading = ref(false)

const submit = () => {
    loading.value = true

    router.post(route("ltu.translation.export"), {}, {
        preserveScroll: true,
        onSuccess: () => {
            loading.value = false

            close()
        },
    });
}

const download = () => {
    downloadLoading.value = true

    fetch(route("ltu.translation.download"))
        .then(async (res) => {
            let blob = await res.blob();
            downloadLoading.value = false;
            const link = document.createElement('a');
            const file = window.URL.createObjectURL(blob);
            link.download = 'lang.zip';
            link.href = file;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);

            downloadLoading.value = false;

            close()
        })
        .catch((error) => {
            toast.error("Something went wrong, please try again.", {
                icon: true,
                position: POSITION.BOTTOM_CENTER,
            })
        });
};
</script>

<template>
    <Head title="Add Languages" />

    <Dialog size="lg">
        <div v-if="canPublish" class="relative flex flex-col items-start justify-center gap-4 px-6 py-4">
            <div class="flex w-full items-start gap-4">
                <div class="flex size-16 shrink-0">
                    <IconPublish class="size-16 text-blue-300" />
                </div>

                <div class="flex-1">
                    <h3 class="text-xl font-semibold leading-6 text-gray-600">
                        Publish Translations
                    </h3>

                    <p class="mt-1 text-sm text-gray-500">
                        Be cautious when publishing, as this action will update your project with all translations and changes made in the database, overwriting project files.
                    </p>
                </div>
            </div>

            <div class="w-full text-center">
                <Alert v-if="!isProductionEnv" variant="warning" class="text-left">
                    <strong>Warning:</strong> This is a Production Environment. Publishing translations will causing issues with version control and other developers, Please use the download button below instead.
                </Alert>

                <BaseButton v-if="!isProductionEnv" :disabled="loading || downloadLoading" :is-loading="downloadLoading" variant="dark" size="lg" class="mt-4" full-width target="_blank" @click="download">
                    <ArrowDownTrayIcon class="size-4" />

                    <span>Download</span>
                </BaseButton>
            </div>
        </div>

        <div v-else class="relative flex flex-col items-start justify-center gap-4 px-6 py-4">
            <div class="mx-auto flex size-12 shrink-0 items-center justify-center">
                <span role="img" class="text-4xl">🤔</span>
            </div>

            <div class="w-full text-center">
                <h3 class="text-xl font-semibold leading-6 text-gray-600">
                    What are you trying to do?
                </h3>

                <p class="mt-4 text-sm text-gray-500">
                    Add languages to your project, then come back to publish translations when you're ready.
                </p>
            </div>
        </div>

        <div class="grid grid-cols-1 gap-6 border-t px-6 py-4" :class="{ 'md:grid-cols-2': canPublish }">
            <BaseButton variant="secondary" type="button" size="lg" tabindex="1" @click="close"> Close </BaseButton>

            <BaseButton v-if="canPublish" variant="primary" type="button" size="lg" :disabled="loading || downloadLoading" :is-loading="loading" @click="submit">
                Publish
            </BaseButton>
        </div>
    </Dialog>
</template>
