// resources/js/Pages/Auth/Login.tsx
import { useEffect } from 'react';
import GuestLayout from '@/Layouts/GuestLayout';
import {Alert, Button, Checkbox, Form, Input} from 'antd';
import {Head, Link, useForm, usePage} from '@inertiajs/react';

const Login = ({ status }: { status?: string, canResetPassword: boolean }) => {
    const { flash } = usePage().props as unknown as { flash: { message?: string } };

    const { data, setData, post, processing, errors, reset } = useForm({
        email: '',
        password: '',
        remember: false,
    });

    useEffect(() => {
        return () => {
            reset('password');
        };
    }, []);

    const submit = () => {
        post(route('ltu.login.attempt'));
    };

    return (
        <GuestLayout
            title="Sign in to your account"
        >
            <Head title="Sign in" />

            <div className="mx-auto w-full max-w-sm lg:w-96">
                {(flash.message || status) && (
                    <Alert
                        message={flash.message || status}
                        type={status ? 'success' : 'error'}
                        showIcon
                        className="mt-4"
                    />
                )}

                <div className="mt-6">
                    <Form
                        name="basic"
                        layout='vertical'
                        initialValues={data}
                        onFieldsChange={(changedFields) => {
                            changedFields.forEach(item => {
                                setData(item.name[0], item.value);
                            })
                        }}
                        onFinish={submit}
                        autoComplete="off"
                    >
                        <Form.Item
                            name="email"
                            label="Email Address"
                            validateStatus={errors.email && 'error'}
                            help={errors.email}
                        >
                            <Input
                                type="email"
                                size="large"
                                placeholder="Enter your email address"
                                autoComplete="username"
                            />
                        </Form.Item>

                        <Form.Item
                            name="password"
                            label="Password"
                            validateStatus={errors.password && 'error'}
                            help={errors.password}
                        >
                            <Input.Password
                                size="large"
                                placeholder="Enter your password"
                                autoComplete="current-password"
                            />
                        </Form.Item>

                        <div className="flex items-center justify-between">
                            <Form.Item
                                name="remember"
                                valuePropName="checked"
                                className="mb-0"
                            >
                                <Checkbox>Remember me</Checkbox>
                            </Form.Item>

                            <Link href={route('ltu.password.request')} className="link">
                                Forgot your password?
                            </Link>
                        </div>

                        <Button className="mt-4" size="large" type="primary" htmlType="submit" loading={processing} block>
                            Sign in
                        </Button>
                    </Form>
                </div>
            </div>
        </GuestLayout>
    );
}

export default Login;

// resources/views/pages/auth/login.vue
<script setup lang="ts">
defineProps<{
    canResetPassword?: boolean
    status?: string
}>()

const form = useForm({
    email: "",
    password: "",
    remember: false,
})

const submit = () => {
    form.post(route("ltu.login.attempt"), {
        onFinish: () => {
            form.reset("password")
        },
    })
}
</script>

<template>
    <LayoutGuest>
        <Head title="Log in" />

        <template #title> Sign in to your account</template>

        <div v-if="status" class="mb-4 text-sm font-medium text-green-600">
            {{ status }}
        </div>

        <form class="space-y-6" @submit.prevent="submit">
            <div class="space-y-1">
                <InputLabel for="email" value="Email Address" class="sr-only" />

                <InputText id="email" v-model="form.email" :error="form.errors.email" type="email" required autofocus placeholder="Email address" autocomplete="username" class="bg-gray-50" />

                <InputError :message="form.errors.email" />
            </div>

            <div class="space-y-1">
                <InputLabel for="password" value="Password" class="sr-only" />

                <InputPassword id="password" v-model="form.password" :error="form.errors.password" required autocomplete="current-password" placeholder="Password" class="bg-gray-50" />

                <InputError :message="form.errors.password" />
            </div>

            <BaseButton type="submit" size="lg" variant="secondary" :is-loading="form.processing" full-width> Continue </BaseButton>
        </form>

        <div class="mt-8 flex w-full justify-center">
            <Link :href="route('ltu.password.request')" class="text-xs font-medium text-gray-500 hover:text-blue-500"> Forgot your password? </Link>
        </div>
    </LayoutGuest>
</template>
