// resources/js/pages/translations/auth/login.tsx
import { Head, useForm } from '@inertiajs/react';
import { show as registerShow } from '@/actions/Outhebox/Translations/Http/Controllers/Auth/RegisterController';
import TextLink from '@/components/text-link';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Field, FieldError, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Spinner } from '@/components/ui/spinner';
import AuthLayout from '@/layouts/auth-layout';
import { store } from '@/routes/ltu/login';

type Props = {
    canRegister: boolean;
};

export default function Login({ canRegister }: Props) {
    const form = useForm({
        email: '',
        password: '',
        remember: false,
    });

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        form.post(store.url(), {
            onFinish: () => form.reset('password'),
        });
    };

    return (
        <AuthLayout
            title="Log in to Translations"
            description="Enter your email and password below to log in"
        >
            <Head title="Log in" />

            <form onSubmit={handleSubmit} className="flex flex-col gap-6">
                <div className="grid gap-6">
                    <Field data-invalid={!!form.errors.email}>
                        <FieldLabel htmlFor="email">Email address</FieldLabel>
                        <Input
                            id="email"
                            type="email"
                            value={form.data.email}
                            onChange={(e) =>
                                form.setData('email', e.target.value)
                            }
                            required
                            autoFocus
                            autoComplete="email"
                            placeholder="email@example.com"
                            aria-invalid={!!form.errors.email}
                        />
                        <FieldError>{form.errors.email}</FieldError>
                    </Field>

                    <Field data-invalid={!!form.errors.password}>
                        <FieldLabel htmlFor="password">Password</FieldLabel>
                        <Input
                            id="password"
                            type="password"
                            value={form.data.password}
                            onChange={(e) =>
                                form.setData('password', e.target.value)
                            }
                            required
                            autoComplete="current-password"
                            placeholder="Password"
                            aria-invalid={!!form.errors.password}
                        />
                        <FieldError>{form.errors.password}</FieldError>
                    </Field>

                    <div className="flex items-center space-x-3">
                        <Checkbox
                            id="remember"
                            checked={form.data.remember}
                            onCheckedChange={(checked) =>
                                form.setData('remember', checked === true)
                            }
                        />
                        <Label htmlFor="remember">Remember me</Label>
                    </div>

                    <Button
                        type="submit"
                        className="mt-4 w-full"
                        disabled={form.processing}
                    >
                        {form.processing && <Spinner />}
                        Log in
                    </Button>
                </div>

                {canRegister && (
                    <div className="text-center text-sm text-muted-foreground">
                        Don't have an account?{' '}
                        <TextLink href={registerShow.url()}>Sign up</TextLink>
                    </div>
                )}
            </form>
        </AuthLayout>
    );
}

// resources/views/pages/auth/login.vue
<script setup lang="ts">
defineProps<{
    status?: string
}>()

const form = useForm({
    email: "",
    password: "",
    remember: false,
})

const submit = () => {
    form.post(route("ltu.login.attempt"), {
        onFinish: () => {
            form.reset("password")
        },
    })
}
</script>

<template>
    <LayoutGuest>
        <Head title="Log in" />

        <template #title> Sign in to your account</template>

        <div v-if="status" class="mb-4 text-sm font-medium text-green-600">
            {{ status }}
        </div>

        <form class="space-y-6" @submit.prevent="submit">
            <div class="space-y-1">
                <InputLabel for="email" value="Email Address" class="sr-only" />

                <InputText id="email" v-model="form.email" :error="form.errors.email" type="email" required autofocus placeholder="Email address" autocomplete="username" class="bg-gray-50" />

                <InputError :message="form.errors.email" />
            </div>

            <div class="space-y-1">
                <InputLabel for="password" value="Password" class="sr-only" />

                <InputPassword id="password" v-model="form.password" :error="form.errors.password" required autocomplete="current-password" placeholder="Password" class="bg-gray-50" />

                <InputError :message="form.errors.password" />
            </div>

            <BaseButton type="submit" size="lg" variant="secondary" :is-loading="form.processing" full-width> Continue </BaseButton>
        </form>

        <div class="mt-8 flex w-full justify-center">
            <Link :href="route('ltu.password.request')" class="text-xs font-medium text-gray-500 hover:text-blue-500"> Forgot your password? </Link>
        </div>
    </LayoutGuest>
</template>
