// resources/js/Pages/Auth/ResetPassword.tsx
import { useEffect } from "react";
import {Head, useForm} from "@inertiajs/react";
import GuestLayout from "@/Layouts/GuestLayout";
import {Button, Form, Input, Typography} from "antd";

export default function ResetPassword({ token, email }: { token: string, email: string }) {
    const { Title } = Typography;
    const { data, setData, post, processing, errors, reset } = useForm({
        token: token,
        email: email,
        password: '',
        password_confirmation: '',
    });

    useEffect(() => {
        return () => {
            reset('password', 'password_confirmation');
        };
    }, []);

    const submit = () => {
        post(route('ltu.password.update'));
    };

    return (
        <GuestLayout
            title="Reset your password"
        >
            <Head title="Reset Password"/>

            <div className="mt-4">
                <Form
                    name="basic"
                    layout='vertical'
                    initialValues={data}
                    onFieldsChange={(changedFields) => {
                        changedFields.forEach(item => {
                            setData(item.name[0], item.value);
                        })
                    }}
                    onFinish={submit}
                    autoComplete="off"
                >
                    <Form.Item
                        label="Password"
                        name="password"
                        validateStatus={errors.password && 'error'}
                        help={errors.password}
                    >
                        <Input.Password size="large" placeholder="Enter your password"/>
                    </Form.Item>

                    <Form.Item
                        label="Confirm Password"
                        name="password_confirmation"
                        validateStatus={errors.password_confirmation && 'error'}
                        help={errors.password_confirmation}
                    >
                        <Input.Password size="large" placeholder="Confirm your password"/>
                    </Form.Item>

                    <Button className="mt-1" size="large" type="primary" htmlType="submit" loading={processing} block>
                        Reset Password
                    </Button>
                </Form>
            </div>
        </GuestLayout>
    );
}

// resources/views/pages/auth/reset-password.vue
<script setup lang="ts">
const props = defineProps<{
    email: string;
    token: string;
}>();

const form = useForm({
    token: props.token,
    email: props.email,
    password: '',
    password_confirmation: '',
});

const submit = () => {
    form.post(route('ltu.password.store'), {
        onFinish: () => {
            form.reset('password', 'password_confirmation');
        },
    });
};
</script>

<template>
    <LayoutGuest>
        <Head title="Reset Password" />

        <template #title> Reset Password </template>

        <template #subtitle> Ensure your new password is at least 8 characters long to ensure security. </template>

        <form class="space-y-6" @submit.prevent="submit">
            <div class="space-y-1">
                <InputLabel for="email" value="Email" />

                <InputText
                    id="email"
                    v-model="form.email"
                    :error="form.errors.email"
                    type="email"
                    required
                    autofocus
                    autocomplete="username"
                />

                <InputError :message="form.errors.email" />
            </div>

            <div class="space-y-1">
                <InputLabel for="password" value="Password" />

                <InputText
                    id="password"
                    v-model="form.password"
                    :error="form.errors.password"
                    type="password"
                    required
                    autocomplete="new-password"
                />

                <InputError :message="form.errors.password" />
            </div>

            <div class="space-y-1">
                <InputLabel for="password_confirmation" value="Confirm Password" />

                <InputText
                    id="password_confirmation"
                    v-model="form.password_confirmation"
                    :error="form.errors.password_confirmation"
                    type="password"
                    required
                    autocomplete="new-password"
                />

                <InputError :message="form.errors.password_confirmation" />
            </div>

            <BaseButton type="submit" variant="primary" :is-loading="form.processing" full-width>
                Reset Password
            </BaseButton>
        </form>
    </LayoutGuest>
</template>
