// resources/js/Pages/Translations/Source/Index.tsx
import React from "react";
import { Head, Link, router } from "@inertiajs/react";
import IconKey from "@/Components/Icons/IconKey";
import { PageProps, Phrase, PhrasePagination, Translation } from "@/types";
import DashboardLayout from '@/Layouts/DashboardLayout';
import IconEmptyTranslations from "@/Components/Icons/IconEmptyTranslations";
import { Button, Empty, Table, TableColumnsType, TableProps, Tooltip, Typography } from "antd";
import { PencilIcon, PlusIcon, TrashIcon } from "@heroicons/react/24/outline";
import CountryFlag from "@/Components/Language/Flag";
import { ArrowRightIcon } from "@heroicons/react/16/solid";
import RenderPhraseWithParameters
    from "@/Components/Phrase/RenderPhraseWithParameters"

interface DataType {
    key: React.Key;
    uuid: string;
    value: React.ReactNode;
    string: React.ReactNode;
    translate: React.ReactNode;
    delete: React.ReactNode;
}

const rowSelection: TableProps<DataType>['rowSelection'] = {
    onChange: (selectedRowKeys: React.Key[], selectedRows: DataType[]) => {
        console.log(`selectedRowKeys: ${selectedRowKeys}`, 'selectedRows: ', selectedRows);
    },
    getCheckboxProps: (record: DataType) => ({
        key: record.key,
        disabled: false,
    }),
};

export interface Props {
    auth: PageProps['auth'];
    phrases: PhrasePagination;
    translation: Translation;
    files: any;
    filter: any;
}

const SourceTranslationsIndex: React.FC<Props> = ({ auth, phrases, translation, files, filter }) => {
    const handleTableChange: TableProps<DataType>['onChange'] = (pagination, filters, sorter, extra) => {
        router.get(route('ltu.source_translation'), {
            page: pagination.current,
            per_page: pagination.pageSize,
        }, {
            preserveState: true,
            replace: true,
        });
    };

    const columns: TableColumnsType<DataType> = [
        {
            title: 'Key',
            dataIndex: 'value',
            width: '35%',
        },
        {
            title: 'String',
            dataIndex: 'string',
            width: '45%',
        },
        {
            title: (
                <Tooltip title="Add new key">
                    <Button block type="default" title="Add new key" className="border-none h-14 bg-transparent rounded-none">
                        <PlusIcon className="size-5" />
                    </Button>
                </Tooltip>
            ),
            className: '!p-0',
            dataIndex: 'translate',
            width: '5%',
        },
        {
            title: (
                <Tooltip title="Delete Selected Keys">
                    <Button block disabled type="default" title="Delete Selected Keys" className="border-none h-14 bg-transparent rounded-none">
                        <TrashIcon className="size-5" />
                    </Button>
                </Tooltip>
            ),
            className: '!p-0',
            dataIndex: 'delete',
            width: '5%',
        },
    ];

    const data: DataType[] = phrases.data.map((phrase: Phrase) => ({
        key: phrase.uuid,
        uuid: phrase.uuid,
        value: (
            <div className="flex group items-center cursor-pointer gap-2 max-w-max truncate rounded-md border bg-white px-1.5 py-0.5 text-sm font-medium text-gray-600 hover:border-blue-400 hover:bg-blue-50 hover:text-blue-600">
                <IconKey className="size-4 text-gray-400 group-hover:text-blue-400" />
                <span>{phrase.key}</span>
            </div>
        ),
        string: (
            <RenderPhraseWithParameters
                value={phrase.value}
                parameters={phrase.parameters}
            />
        ),
        translate: (
            <Link href={route('ltu.phrases.edit', { translation: translation.id, phrase: phrase.uuid })}>
                <Tooltip title="Translate">
                    <Button block type="default" title="Translate" className="border-none h-14 text-gray-400 bg-transparent rounded-none">
                        <PencilIcon className="size-5" />
                    </Button>
                </Tooltip>
            </Link>
        ),
        delete: (
            <Tooltip title="Delete">
                <Button block type="default" title="Delete" className="border-none h-14 text-gray-400 bg-transparent rounded-none">
                    <TrashIcon className="size-5" />
                </Button>
            </Tooltip>
        ),
    }));

    return (
        <DashboardLayout
            user={auth.user}
            header={
                <>
                    <div className="flex w-full items-center gap-3 py-2">
                        <Link href="#" className="flex items-center gap-2 rounded-md border border-transparent bg-gray-50 px-2 py-1 hover:border-blue-400 hover:bg-blue-100">
                            <div className="h-5 shrink-0">
                                <CountryFlag countryCode={translation.language.code} />
                            </div>
                            <div className="flex items-center space-x-2">
                                <div className="text-sm font-semibold text-gray-600">
                                    {translation.language.name}
                                </div>
                            </div>
                        </Link>
                        <div className="rounded-md border bg-white px-1.5 py-0.5 text-sm text-gray-500">
                            {translation.language.code}
                        </div>
                    </div>

                    <Link href="#" className="flex size-10 items-center justify-center rounded-full bg-gray-100 p-1 hover:bg-gray-200">
                        <ArrowRightIcon className="size-6 text-gray-400" />
                    </Link>
                </>
            }
        >
            <Head title={translation.language.name} />

            <div className="rounded-lg shadow overflow-hidden mx-auto">
                <Table
                    bordered
                    columns={columns}
                    dataSource={data}
                    onChange={handleTableChange}
                    pagination={{
                        total: phrases.meta.total,
                        showSizeChanger: true,
                        position: ['bottomCenter'],
                        pageSize: phrases.meta.per_page,
                        current: phrases.meta.current_page,
                        defaultPageSize: phrases.meta.per_page,
                        showTotal: (total, range) => `${range[0]}-${range[1]} of ${total} items`,
                    }}
                    rowSelection={{
                        type: 'checkbox',
                        columnWidth: '5%',
                        ...rowSelection,
                    }}
                    locale={{
                        emptyText: (
                            <Empty
                                className="py-24"
                                image={<IconEmptyTranslations className="size-24 mb-4 fill-gray-300" />}
                                description={
                                    <Typography.Text>
                                        There are no keys to translate your project to. <br /> Add the first one and start translating.
                                    </Typography.Text>
                                }
                            >
                                <Button
                                    size="large"
                                    type="primary"
                                    className="uppercase text-sm font-medium tracking-tight"
                                    icon={<PlusIcon className="size-5" />}
                                >
                                    Add your first key
                                </Button>
                            </Empty>
                        )
                    }}>
                </Table>
            </div>
        </DashboardLayout>
    );
}

export default SourceTranslationsIndex;

// resources/views/pages/source/index.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import { Translation } from "../../../scripts/types"

const props = defineProps<{
    phrases: Object,
    translation: Translation,
}>()

const form = useForm({
    search: ref(''),
    status: ref(''),
});

watch(form, () => {
    form.get(route('ltu.translation.source_language', { translation: props.translation.id }), {
        replace: true,
        onSuccess: () => {
            form.reset();
        },
    });
});
</script>
<template>
    <Head title="Base Language" />

    <LayoutDashboard>
        <div class="w-full bg-white shadow">
            <div class="mx-auto flex w-full max-w-7xl items-center justify-between px-6 lg:px-8">
                <div class="flex w-full items-center">
                    <div class="flex w-full items-center gap-3 py-4">
                        <Link href="#" class="flex items-center gap-2 rounded-md border border-transparent bg-gray-50 px-2 py-1 hover:border-blue-400 hover:bg-blue-100">
                            <div class="h-5 shrink-0">
                                <Flag :country-code="translation.language.code" width="w-5" />
                            </div>

                            <div class="flex items-center space-x-2">
                                <div class="text-sm font-semibold text-gray-600" v-text="translation.language.name"></div>
                            </div>
                        </Link>

                        <div class="rounded-md border bg-white px-1.5 py-0.5 text-sm text-gray-500" v-text="translation.language.code"></div>
                    </div>
                </div>

                <Link v-tooltip="'Go back'" :href="route('ltu.translation.index')" class="flex h-10 w-10 items-center justify-center rounded-full bg-gray-100 p-1 hover:bg-gray-200">
                    <IconArrowRight class="h-6 w-6 text-gray-400" />
                </Link>
            </div>
        </div>

        <div class="mx-auto max-w-7xl px-6 py-10 lg:px-8">
            <div class="w-full divide-y overflow-hidden rounded-md bg-white shadow">
                <div class="grid w-full grid-cols-8 justify-between px-4 py-3">
                    <div class="col-span-2">
                        <InputText placeholder="Search" v-model="form.search" size="md" />
                    </div>

                    <div class="col-span-4"></div>

                    <div class="col-span-2">
                        <InputNativeSelect
                            size="md"
                            id="status"
                            placeholder="Filter by status"
                            v-model="form.status"
                            :error="form.errors.status"
                            :items="[
                                { value: 'translated', label: 'Translated' },
                                { value: 'untranslated', label: 'Untranslated' },
                            ]"
                        />
                    </div>
                </div>

                <div class="w-full shadow-md">
                    <div class="flex h-14 w-full divide-x">
                        <div class="flex w-12 items-center justify-center p-4">
                            <InputCheckbox />
                        </div>

                        <div class="hidden w-20 items-center justify-center px-4 md:flex">
                            <span class="text-sm font-medium text-gray-400">State</span>
                        </div>

                        <div class="grid w-full grid-cols-2 divide-x">
                            <div class="flex w-full items-center justify-start px-4">
                                <span class="text-sm font-medium text-gray-400">Key</span>
                            </div>

                            <div class="flex w-full items-center justify-start px-4">
                                <span class="text-sm font-medium text-gray-400">String</span>
                            </div>
                        </div>

                        <div class="grid divide-x w-36 grid-cols-2">
                            <Link v-tooltip="'Add New Key'" :href="route('ltu.translation.source_language.add_source_key')" class="group flex items-center justify-center hover:bg-blue-50">
                                <IconPlus class="h-5 w-5 text-gray-400 group-hover:text-blue-600" />
                            </Link>

                            <div class="flex items-center justify-center">
                                <IconEllipsisVertical class="h-5 w-5 text-gray-400" />
                            </div>
                        </div>
                    </div>
                </div>

                <div v-for="phrase in phrases.data" :key="phrase.id" class="w-full hover:bg-gray-100">
                    <div class="flex h-14 w-full divide-x">
                        <div class="flex w-12 items-center justify-center p-4">
                            <InputCheckbox />
                        </div>

                        <div class="hidden w-20 items-center justify-center px-4 md:flex" :class="{ 'bg-green-50': phrase.state, 'hover:bg-green-100': phrase.state }">
                            <IconCheck v-if="phrase.state" class="h-5 w-5 text-green-600" />

                            <IconLanguage v-else class="h-5 w-5 text-gray-500" />
                        </div>

                        <Link :href="route('ltu.translation.source_language.edit', phrase.uuid)" class="grid w-full grid-cols-2 divide-x">
                            <div class="flex w-full items-center justify-start px-4">
                                <div class="truncate rounded-md border bg-white px-1.5 py-0.5 text-sm font-medium text-gray-600 hover:border-blue-400 hover:bg-blue-50 hover:text-blue-600">
                                    {{ phrase.key }}
                                </div>
                            </div>

                            <div class="flex w-full items-center justify-start px-4">
                                <div class="w-full truncate whitespace-nowrap text-sm font-medium text-gray-600">
                                    {{ phrase.value }}
                                </div>
                            </div>
                        </Link>

                        <div class="grid divide-x w-36 grid-cols-2">
                            <Link v-tooltip="'Edit'" :href="route('ltu.translation.source_language.edit', phrase.uuid)" class="group flex items-center justify-center px-3 hover:bg-blue-50">
                                <IconPencil class="h-5 w-5 text-gray-400 group-hover:text-blue-600" />
                            </Link>

                            <Link v-tooltip="'Delete'" :href="route('ltu.confirmation')" type="button" class="group flex items-center justify-center px-3 hover:bg-red-50">
                                <IconTrash class="h-5 w-5 text-gray-400 group-hover:text-red-600" />
                            </Link>
                        </div>
                    </div>
                </div>

                <Pagination :links="phrases.links" :meta="phrases.meta" />
            </div>
        </div>
    </LayoutDashboard>
</template>
