// resources/views/pages/auth/register.vue
<script setup lang="ts">
const form = useForm({
    name: '',
    email: '',
    password: '',
    password_confirmation: '',
});

const submit = () => {
    form.post(route('ltu.register'), {
        onFinish: () => {
            form.reset('password', 'password_confirmation');
        },
    });
};
</script>

<template>
    <LayoutGuest>
        <Head title="Create an account" />

        <template #title> Create an account </template>

        <template #subtitle>
            Already have an account?
            <Link :href="route('ltu.login')" class="font-semibold text-blue-600 hover:text-blue-500">
                Sign in
            </Link>
        </template>

        <form class="space-y-6" @submit.prevent="submit">
            <div class="space-y-1">
                <InputLabel for="name" value="Name" />

                <InputText
                    id="name"
                    v-model="form.name"
                    :error="form.errors.name"
                    type="text"
                    required
                    autofocus
                    autocomplete="name"
                />

                <InputError :message="form.errors.name" />
            </div>

            <div class="space-y-1">
                <InputLabel for="email" value="Email Address" />

                <InputText
                    id="email"
                    v-model="form.email"
                    :error="form.errors.email"
                    type="email"
                    required
                    autocomplete="username"
                />

                <InputError :message="form.errors.email" />
            </div>

            <div class="space-y-1">
                <InputLabel for="password" value="Password" />

                <InputText
                    id="password"
                    v-model="form.password"
                    :error="form.errors.password"
                    type="password"
                    required
                    autocomplete="new-password"
                />

                <InputError :message="form.errors.password" />
            </div>

            <div class="space-y-1">
                <InputLabel for="password_confirmation" value="Confirm Password" />

                <InputText
                    id="password_confirmation"
                    v-model="form.password_confirmation"
                    :error="form.errors.password_confirmation"
                    type="password"
                    required
                    autocomplete="new-password"
                />

                <InputError :message="form.errors.password_confirmation" />
            </div>

            <BaseButton type="submit" variant="primary" :is-loading="form.processing" full-width>
                Create account
            </BaseButton>
        </form>

        <div class="mt-10">
            <div class="relative">
                <div
                    class="absolute inset-0 flex items-center"
                    aria-hidden="true">
                    <div class="w-full border-t border-gray-200" />
                </div>

                <div class="relative flex justify-center text-sm font-medium leading-6">
                    <span class="bg-white px-6 text-gray-900">Or continue with</span>
                </div>
            </div>

            <div class="mt-6 grid grid-cols-1 gap-4">
                <Link href="#" class="btn btn-lg border border-slate-200 text-gray-700 transition duration-150 hover:border-gray-400 hover:text-gray-900 hover:shadow">
                    <IconGoogle class="h-5 w-5" />

                    <span>Continue with Google</span>
                </Link>
            </div>
        </div>
    </LayoutGuest>
</template>

// resources/js/pages/translations/auth/register.tsx
import { Head, useForm } from '@inertiajs/react';
import { show as loginShow } from '@/actions/Outhebox/Translations/Http/Controllers/Auth/LoginController';
import TextLink from '@/components/text-link';
import { Button } from '@/components/ui/button';
import { Field, FieldError, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { Spinner } from '@/components/ui/spinner';
import AuthLayout from '@/layouts/auth-layout';
import { store } from '@/routes/ltu/register';

export default function Register() {
    const form = useForm({
        name: '',
        email: '',
        password: '',
        password_confirmation: '',
    });

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        form.post(store.url(), {
            onFinish: () => form.reset('password', 'password_confirmation'),
        });
    };

    return (
        <AuthLayout
            title="Create a contributor account"
            description="Enter your details below to create your account"
        >
            <Head title="Register" />

            <form onSubmit={handleSubmit} className="flex flex-col gap-6">
                <div className="grid gap-6">
                    <Field data-invalid={!!form.errors.name}>
                        <FieldLabel htmlFor="name">Name</FieldLabel>
                        <Input
                            id="name"
                            type="text"
                            value={form.data.name}
                            onChange={(e) =>
                                form.setData('name', e.target.value)
                            }
                            required
                            autoFocus
                            autoComplete="name"
                            placeholder="Full name"
                            aria-invalid={!!form.errors.name}
                        />
                        <FieldError>{form.errors.name}</FieldError>
                    </Field>

                    <Field data-invalid={!!form.errors.email}>
                        <FieldLabel htmlFor="email">Email address</FieldLabel>
                        <Input
                            id="email"
                            type="email"
                            value={form.data.email}
                            onChange={(e) =>
                                form.setData('email', e.target.value)
                            }
                            required
                            autoComplete="email"
                            placeholder="email@example.com"
                            aria-invalid={!!form.errors.email}
                        />
                        <FieldError>{form.errors.email}</FieldError>
                    </Field>

                    <Field data-invalid={!!form.errors.password}>
                        <FieldLabel htmlFor="password">Password</FieldLabel>
                        <Input
                            id="password"
                            type="password"
                            value={form.data.password}
                            onChange={(e) =>
                                form.setData('password', e.target.value)
                            }
                            required
                            autoComplete="new-password"
                            placeholder="Password"
                            aria-invalid={!!form.errors.password}
                        />
                        <FieldError>{form.errors.password}</FieldError>
                    </Field>

                    <Field data-invalid={!!form.errors.password_confirmation}>
                        <FieldLabel htmlFor="password_confirmation">
                            Confirm password
                        </FieldLabel>
                        <Input
                            id="password_confirmation"
                            type="password"
                            value={form.data.password_confirmation}
                            onChange={(e) =>
                                form.setData(
                                    'password_confirmation',
                                    e.target.value,
                                )
                            }
                            required
                            autoComplete="new-password"
                            placeholder="Confirm password"
                            aria-invalid={!!form.errors.password_confirmation}
                        />
                        <FieldError>
                            {form.errors.password_confirmation}
                        </FieldError>
                    </Field>

                    <Button
                        type="submit"
                        className="mt-2 w-full"
                        disabled={form.processing}
                    >
                        {form.processing && <Spinner />}
                        Create account
                    </Button>
                </div>

                <div className="text-center text-sm text-muted-foreground">
                    Already have an account?{' '}
                    <TextLink href={loginShow.url()}>Log in</TextLink>
                </div>
            </form>
        </AuthLayout>
    );
}
